import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  poweredByHeader: false,
  compress: true,
  experimental: {
    optimizeCss: true,
  },
  images: {
    formats: ['image/avif', 'image/webp'],
    minimumCacheTTL: 31536000,
  },
  async redirects() {
    return [
      { source: "/calculator", destination: "/", permanent: true },
      { source: "/hr/week/hourly-paycheck-calculator", destination: "/hourly-paycheck-calculator", permanent: true },
      { source: "/bonus-calculator", destination: "/bonus-tax-calculator", permanent: true },
      { source: "/bonus-calculator/:state", destination: "/bonus-tax-calculator/:state", permanent: true },
      { source: "/unemployment-calculator", destination: "/unemployment-calculator/california", permanent: false },
      { source: "/overtime-calculator", destination: "/overtime-calculator/california", permanent: false },
      { source: "/blog/alabama-paycheck-calculator", destination: "/alabama-paycheck-calculator", permanent: true },
      { source: "/blog/alaska-paycheck-calculator", destination: "/alaska-paycheck-calculator", permanent: true },
      { source: "/blog/arizona-paycheck-calculator", destination: "/arizona-paycheck-calculator", permanent: true },
      { source: "/blog/arkansas-paycheck-calculator", destination: "/arkansas-paycheck-calculator", permanent: true },
      { source: "/blog/california-paycheck-calculator", destination: "/california-paycheck-calculator", permanent: true },
      { source: "/blog/colorado-paycheck-calculator", destination: "/colorado-paycheck-calculator", permanent: true },
      { source: "/blog/connecticut-paycheck-calculator", destination: "/connecticut-paycheck-calculator", permanent: true },
      { source: "/blog/delaware-paycheck-calculator", destination: "/delaware-paycheck-calculator", permanent: true },
      { source: "/blog/florida-paycheck-calculator", destination: "/florida-paycheck-calculator", permanent: true },
      { source: "/blog/georgia-paycheck-calculator", destination: "/georgia-paycheck-calculator", permanent: true },
      { source: "/blog/hawaii-paycheck-calculator", destination: "/hawaii-paycheck-calculator", permanent: true },
      { source: "/blog/idaho-paycheck-calculator", destination: "/idaho-paycheck-calculator", permanent: true },
      { source: "/blog/illinois-paycheck-calculator", destination: "/illinois-paycheck-calculator", permanent: true },
      { source: "/blog/indiana-paycheck-calculator", destination: "/indiana-paycheck-calculator", permanent: true },
      { source: "/blog/iowa-paycheck-calculator", destination: "/iowa-paycheck-calculator", permanent: true },
      { source: "/blog/kansas-paycheck-calculator", destination: "/kansas-paycheck-calculator", permanent: true },
      { source: "/blog/kentucky-paycheck-calculator", destination: "/kentucky-paycheck-calculator", permanent: true },
      { source: "/blog/louisiana-paycheck-calculator", destination: "/louisiana-paycheck-calculator", permanent: true },
      { source: "/blog/maine-paycheck-calculator", destination: "/maine-paycheck-calculator", permanent: true },
      { source: "/blog/maryland-paycheck-calculator", destination: "/maryland-paycheck-calculator", permanent: true },
      { source: "/blog/massachusetts-paycheck-calculator", destination: "/massachusetts-paycheck-calculator", permanent: true },
      { source: "/blog/michigan-paycheck-calculator", destination: "/michigan-paycheck-calculator", permanent: true },
      { source: "/blog/minnesota-paycheck-calculator", destination: "/minnesota-paycheck-calculator", permanent: true },
      { source: "/blog/mississippi-paycheck-calculator", destination: "/mississippi-paycheck-calculator", permanent: true },
      { source: "/blog/missouri-paycheck-calculator", destination: "/missouri-paycheck-calculator", permanent: true },
      { source: "/blog/montana-paycheck-calculator", destination: "/montana-paycheck-calculator", permanent: true },
      { source: "/blog/nebraska-paycheck-calculator", destination: "/nebraska-paycheck-calculator", permanent: true },
      { source: "/blog/nevada-paycheck-calculator", destination: "/nevada-paycheck-calculator", permanent: true },
      { source: "/blog/new-hampshire-paycheck-calculator", destination: "/new-hampshire-paycheck-calculator", permanent: true },
      { source: "/blog/new-jersey-paycheck-calculator", destination: "/new-jersey-paycheck-calculator", permanent: true },
      { source: "/blog/new-mexico-paycheck-calculator", destination: "/new-mexico-paycheck-calculator", permanent: true },
      { source: "/blog/new-york-paycheck-calculator", destination: "/new-york-paycheck-calculator", permanent: true },
      { source: "/blog/north-carolina-paycheck-calculator", destination: "/north-carolina-paycheck-calculator", permanent: true },
      { source: "/blog/north-dakota-paycheck-calculator", destination: "/north-dakota-paycheck-calculator", permanent: true },
      { source: "/blog/ohio-paycheck-calculator", destination: "/ohio-paycheck-calculator", permanent: true },
      { source: "/blog/oklahoma-paycheck-calculator", destination: "/oklahoma-paycheck-calculator", permanent: true },
      { source: "/blog/oregon-paycheck-calculator", destination: "/oregon-paycheck-calculator", permanent: true },
      { source: "/blog/pennsylvania-paycheck-calculator", destination: "/pennsylvania-paycheck-calculator", permanent: true },
      { source: "/blog/rhode-island-paycheck-calculator", destination: "/rhode-island-paycheck-calculator", permanent: true },
      { source: "/blog/south-carolina-paycheck-calculator", destination: "/south-carolina-paycheck-calculator", permanent: true },
      { source: "/blog/south-dakota-paycheck-calculator", destination: "/south-dakota-paycheck-calculator", permanent: true },
      { source: "/blog/tennessee-paycheck-calculator", destination: "/tennessee-paycheck-calculator", permanent: true },
      { source: "/blog/texas-paycheck-calculator", destination: "/texas-paycheck-calculator", permanent: true },
      { source: "/blog/utah-paycheck-calculator", destination: "/utah-paycheck-calculator", permanent: true },
      { source: "/blog/vermont-paycheck-calculator", destination: "/vermont-paycheck-calculator", permanent: true },
      { source: "/blog/virginia-paycheck-calculator", destination: "/virginia-paycheck-calculator", permanent: true },
      { source: "/blog/washington-paycheck-calculator", destination: "/washington-paycheck-calculator", permanent: true },
      { source: "/blog/west-virginia-paycheck-calculator", destination: "/west-virginia-paycheck-calculator", permanent: true },
      { source: "/blog/wisconsin-paycheck-calculator", destination: "/wisconsin-paycheck-calculator", permanent: true },
      { source: "/blog/wyoming-paycheck-calculator", destination: "/wyoming-paycheck-calculator", permanent: true },
      { source: "/minimum-wage/methodology", destination: "/", permanent: true },
    ];
  },
  headers: async () => [
    {
      source: "/(.*)",
      headers: [
        { key: "Cache-Control", value: "public, s-maxage=31536000, stale-while-revalidate=86400" },
        { key: "X-Content-Type-Options", value: "nosniff" },
        { key: "X-Frame-Options", value: "DENY" },
      ],
    },
    {
      source: "/_next/static/(.*)",
      headers: [
        { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
      ],
    },
  ],
};

export default nextConfig;
