import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  compress: true,
  experimental: {
    optimizeCss: true,
  },
  images: {
    formats: ['image/avif', 'image/webp'],
    minimumCacheTTL: 31536000,
  },
  async redirects() {
    return [
      { source: "/calculator", destination: "/", permanent: true },
      { source: "/hr/week/hourly-paycheck-calculator", destination: "/hourly-paycheck-calculator", permanent: true },
      { source: "/bonus-calculator", destination: "/bonus-tax-calculator", permanent: true },
      { source: "/bonus-calculator/:state", destination: "/bonus-tax-calculator/:state", permanent: true },
      { source: "/unemployment-calculator", destination: "/unemployment-calculator/california", permanent: false },
      { source: "/overtime-calculator", destination: "/overtime-calculator/california", permanent: false },
      { source: "/blog/alabama-paycheck-calculator", destination: "/alabama", permanent: true },
      { source: "/blog/alaska-paycheck-calculator", destination: "/alaska", permanent: true },
      { source: "/blog/arizona-paycheck-calculator", destination: "/arizona", permanent: true },
      { source: "/blog/arkansas-paycheck-calculator", destination: "/arkansas", permanent: true },
      { source: "/blog/california-paycheck-calculator", destination: "/california", permanent: true },
      { source: "/blog/colorado-paycheck-calculator", destination: "/colorado", permanent: true },
      { source: "/blog/connecticut-paycheck-calculator", destination: "/connecticut", permanent: true },
      { source: "/blog/delaware-paycheck-calculator", destination: "/delaware", permanent: true },
      { source: "/blog/florida-paycheck-calculator", destination: "/florida", permanent: true },
      { source: "/blog/georgia-paycheck-calculator", destination: "/georgia", permanent: true },
      { source: "/blog/hawaii-paycheck-calculator", destination: "/hawaii", permanent: true },
      { source: "/blog/idaho-paycheck-calculator", destination: "/idaho", permanent: true },
      { source: "/blog/illinois-paycheck-calculator", destination: "/illinois", permanent: true },
      { source: "/blog/indiana-paycheck-calculator", destination: "/indiana", permanent: true },
      { source: "/blog/iowa-paycheck-calculator", destination: "/iowa", permanent: true },
      { source: "/blog/kansas-paycheck-calculator", destination: "/kansas", permanent: true },
      { source: "/blog/kentucky-paycheck-calculator", destination: "/kentucky", permanent: true },
      { source: "/blog/louisiana-paycheck-calculator", destination: "/louisiana", permanent: true },
      { source: "/blog/maine-paycheck-calculator", destination: "/maine", permanent: true },
      { source: "/blog/maryland-paycheck-calculator", destination: "/maryland", permanent: true },
      { source: "/blog/massachusetts-paycheck-calculator", destination: "/massachusetts", permanent: true },
      { source: "/blog/michigan-paycheck-calculator", destination: "/michigan", permanent: true },
      { source: "/blog/minnesota-paycheck-calculator", destination: "/minnesota", permanent: true },
      { source: "/blog/mississippi-paycheck-calculator", destination: "/mississippi", permanent: true },
      { source: "/blog/missouri-paycheck-calculator", destination: "/missouri", permanent: true },
      { source: "/blog/montana-paycheck-calculator", destination: "/montana", permanent: true },
      { source: "/blog/nebraska-paycheck-calculator", destination: "/nebraska", permanent: true },
      { source: "/blog/nevada-paycheck-calculator", destination: "/nevada", permanent: true },
      { source: "/blog/new-hampshire-paycheck-calculator", destination: "/new-hampshire", permanent: true },
      { source: "/blog/new-jersey-paycheck-calculator", destination: "/new-jersey", permanent: true },
      { source: "/blog/new-mexico-paycheck-calculator", destination: "/new-mexico", permanent: true },
      { source: "/blog/new-york-paycheck-calculator", destination: "/new-york", permanent: true },
      { source: "/blog/north-carolina-paycheck-calculator", destination: "/north-carolina", permanent: true },
      { source: "/blog/north-dakota-paycheck-calculator", destination: "/north-dakota", permanent: true },
      { source: "/blog/ohio-paycheck-calculator", destination: "/ohio", permanent: true },
      { source: "/blog/oklahoma-paycheck-calculator", destination: "/oklahoma", permanent: true },
      { source: "/blog/oregon-paycheck-calculator", destination: "/oregon", permanent: true },
      { source: "/blog/pennsylvania-paycheck-calculator", destination: "/pennsylvania", permanent: true },
      { source: "/blog/rhode-island-paycheck-calculator", destination: "/rhode-island", permanent: true },
      { source: "/blog/south-carolina-paycheck-calculator", destination: "/south-carolina", permanent: true },
      { source: "/blog/south-dakota-paycheck-calculator", destination: "/south-dakota", permanent: true },
      { source: "/blog/tennessee-paycheck-calculator", destination: "/tennessee", permanent: true },
      { source: "/blog/texas-paycheck-calculator", destination: "/texas", permanent: true },
      { source: "/blog/utah-paycheck-calculator", destination: "/utah", permanent: true },
      { source: "/blog/vermont-paycheck-calculator", destination: "/vermont", permanent: true },
      { source: "/blog/virginia-paycheck-calculator", destination: "/virginia", permanent: true },
      { source: "/blog/washington-paycheck-calculator", destination: "/washington", permanent: true },
      { source: "/blog/west-virginia-paycheck-calculator", destination: "/west-virginia", permanent: true },
      { source: "/blog/wisconsin-paycheck-calculator", destination: "/wisconsin", permanent: true },
      { source: "/blog/wyoming-paycheck-calculator", destination: "/wyoming", permanent: true },
      { source: "/minimum-wage/methodology", destination: "/", permanent: true },
    ];
  },
  headers: async () => [
    {
      source: "/(.*)",
      headers: [
        { key: "Cache-Control", value: "public, s-maxage=31536000, stale-while-revalidate=86400" },
        { key: "X-Content-Type-Options", value: "nosniff" },
        { key: "X-Frame-Options", value: "DENY" },
      ],
    },
    {
      source: "/_next/static/(.*)",
      headers: [
        { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
      ],
    },
  ],
};

export default nextConfig;
